import { RespondentData } from '../types';
import * as XLSX from 'xlsx';

// 30 Dummy Respondents directly structured from Dental_Screening_30_Responden_Dummy.xlsx
export const DUMMY_EXCEL_RESPONDENTS: Omit<RespondentData, 'id' | 'createdAt'>[] = [
  {
    nama: "R001",
    tanggalPemeriksaan: "2026-07-01",
    tanggalInput: "2026-07-01",
    umur: 10,
    jenisKelamin: "Laki-laki",
    kelompokUmur: "5-10",
    alamat: "Alamat Dummy 01",
    noTelepon: "08100000001",
    namaOrangTua: "Orang Tua R001",
    pendidikan: "SMP",
    pekerjaan: "WIRASWASTA/WIRAUSAHA",
    gigiSulung: { sehat: 15, karies: 2, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 2, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 22, karies: 3, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 3, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 5,
    dmft: 6,
    mukosa: { gusiBerdarah: true, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: true, perluPerawatanTidakSegera: false, perluDirujuk: true, dirujukKe: "puskesmas" },
    createdBy: "System Import"
  },
  {
    nama: "R002",
    tanggalPemeriksaan: "2026-07-02",
    tanggalInput: "2026-07-02",
    umur: 13,
    jenisKelamin: "Perempuan",
    kelompokUmur: "10-18",
    alamat: "Alamat Dummy 02",
    noTelepon: "08100000002",
    namaOrangTua: "Orang Tua R002",
    pendidikan: "SMA",
    pekerjaan: "PEGAWAI SWASTA",
    gigiSulung: { sehat: 11, karies: 4, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 3, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 27, karies: 1, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 0, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 9,
    dmft: 1,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: false, perluDirujuk: false, dirujukKe: "tidak_dirujuk" },
    createdBy: "System Import"
  },
  {
    nama: "R003",
    tanggalPemeriksaan: "2026-07-03",
    tanggalInput: "2026-07-03",
    umur: 8,
    jenisKelamin: "Laki-laki",
    kelompokUmur: "5-10",
    alamat: "Alamat Dummy 03",
    noTelepon: "08100000003",
    namaOrangTua: "Orang Tua R003",
    pendidikan: "S1/D4",
    pekerjaan: "ASN/PNS/PPPK",
    gigiSulung: { sehat: 18, karies: 1, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 0, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 1 },
    gigiTetap: { sehat: 23, karies: 4, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 1, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 1,
    dmft: 5,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: true, perluDirujuk: true, dirujukKe: "puskesmas" },
    createdBy: "System Import"
  },
  {
    nama: "R004",
    tanggalPemeriksaan: "2026-07-04",
    tanggalInput: "2026-07-04",
    umur: 11,
    jenisKelamin: "Perempuan",
    kelompokUmur: "10-18",
    alamat: "Alamat Dummy 04",
    noTelepon: "08100000004",
    namaOrangTua: "Orang Tua R004",
    pendidikan: "SD",
    pekerjaan: "PEGAWAI SWASTA",
    gigiSulung: { sehat: 15, karies: 3, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 1, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 24, karies: 2, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 2, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 5,
    dmft: 4,
    mukosa: { gusiBerdarah: true, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: true, perluPerawatanTidakSegera: false, perluDirujuk: false, dirujukKe: "tidak_dirujuk" },
    createdBy: "System Import"
  },
  {
    nama: "R005",
    tanggalPemeriksaan: "2026-07-05",
    tanggalInput: "2026-07-05",
    umur: 14,
    jenisKelamin: "Laki-laki",
    kelompokUmur: "10-18",
    alamat: "Alamat Dummy 05",
    noTelepon: "08100000005",
    namaOrangTua: "Orang Tua R005",
    pendidikan: "SMP",
    pekerjaan: "PENGURUS/IBU RUMAH TANGGA",
    gigiSulung: { sehat: 16, karies: 0, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 2, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 24, karies: 0, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 3, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 4,
    dmft: 4,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: false, perluDirujuk: true, dirujukKe: "puskesmas" },
    createdBy: "System Import"
  },
  {
    nama: "R006",
    tanggalPemeriksaan: "2026-07-06",
    tanggalInput: "2026-07-06",
    umur: 9,
    jenisKelamin: "Perempuan",
    kelompokUmur: "5-10",
    alamat: "Alamat Dummy 06",
    noTelepon: "08100000006",
    namaOrangTua: "Orang Tua R006",
    pendidikan: "SMA",
    pekerjaan: "WIRASWASTA/WIRAUSAHA",
    gigiSulung: { sehat: 14, karies: 2, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 3, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 1 },
    gigiTetap: { sehat: 24, karies: 3, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 0, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 5,
    dmft: 4,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: true, perluDirujuk: false, dirujukKe: "tidak_dirujuk" },
    createdBy: "System Import"
  },
  {
    nama: "R007",
    tanggalPemeriksaan: "2026-07-07",
    tanggalInput: "2026-07-07",
    umur: 12,
    jenisKelamin: "Laki-laki",
    kelompokUmur: "10-18",
    alamat: "Alamat Dummy 07",
    noTelepon: "08100000007",
    namaOrangTua: "Orang Tua R007",
    pendidikan: "S1/D4",
    pekerjaan: "PEGAWAI SWASTA",
    gigiSulung: { sehat: 15, karies: 4, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 0, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 25, karies: 1, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 1, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 5,
    dmft: 3,
    mukosa: { gusiBerdarah: true, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: true, perluPerawatanTidakSegera: false, perluDirujuk: true, dirujukKe: "puskesmas" },
    createdBy: "System Import"
  },
  {
    nama: "R008",
    tanggalPemeriksaan: "2026-07-08",
    tanggalInput: "2026-07-08",
    umur: 7,
    jenisKelamin: "Perempuan",
    kelompokUmur: "5-10",
    alamat: "Alamat Dummy 08",
    noTelepon: "08100000008",
    namaOrangTua: "Orang Tua R008",
    pendidikan: "SD",
    pekerjaan: "ASN/PNS/PPPK",
    gigiSulung: { sehat: 16, karies: 1, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 1, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 21, karies: 4, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 2, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 4,
    dmft: 7,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: false, perluDirujuk: false, dirujukKe: "tidak_dirujuk" },
    createdBy: "System Import"
  },
  {
    nama: "R009",
    tanggalPemeriksaan: "2026-07-09",
    tanggalInput: "2026-07-09",
    umur: 10,
    jenisKelamin: "Laki-laki",
    kelompokUmur: "5-10",
    alamat: "Alamat Dummy 09",
    noTelepon: "08100000009",
    namaOrangTua: "Orang Tua R009",
    pendidikan: "SMP",
    pekerjaan: "PEGAWAI SWASTA",
    gigiSulung: { sehat: 14, karies: 3, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 2, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 1 },
    gigiTetap: { sehat: 22, karies: 2, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 3, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 5,
    dmft: 6,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: true, perluDirujuk: true, dirujukKe: "puskesmas" },
    createdBy: "System Import"
  },
  {
    nama: "R010",
    tanggalPemeriksaan: "2026-07-10",
    tanggalInput: "2026-07-10",
    umur: 13,
    jenisKelamin: "Perempuan",
    kelompokUmur: "10-18",
    alamat: "Alamat Dummy 10",
    noTelepon: "08100000010",
    namaOrangTua: "Orang Tua R010",
    pendidikan: "SMA",
    pekerjaan: "PENGURUS/IBU RUMAH TANGGA",
    gigiSulung: { sehat: 16, karies: 0, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 3, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 26, karies: 0, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 0, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 4,
    dmft: 2,
    mukosa: { gusiBerdarah: true, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: true, perluPerawatanTidakSegera: false, perluDirujuk: false, dirujukKe: "tidak_dirujuk" },
    createdBy: "System Import"
  },
  {
    nama: "R011",
    tanggalPemeriksaan: "2026-07-11",
    tanggalInput: "2026-07-11",
    umur: 8,
    jenisKelamin: "Laki-laki",
    kelompokUmur: "5-10",
    alamat: "Alamat Dummy 11",
    noTelepon: "08100000011",
    namaOrangTua: "Orang Tua R011",
    pendidikan: "S1/D4",
    pekerjaan: "WIRASWASTA/WIRAUSAHA",
    gigiSulung: { sehat: 16, karies: 2, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 0, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 22, karies: 3, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 1, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 4,
    dmft: 6,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: false, perluDirujuk: true, dirujukKe: "puskesmas" },
    createdBy: "System Import"
  },
  {
    nama: "R012",
    tanggalPemeriksaan: "2026-07-12",
    tanggalInput: "2026-07-12",
    umur: 11,
    jenisKelamin: "Perempuan",
    kelompokUmur: "10-18",
    alamat: "Alamat Dummy 12",
    noTelepon: "08100000012",
    namaOrangTua: "Orang Tua R012",
    pendidikan: "SD",
    pekerjaan: "PEGAWAI SWASTA",
    gigiSulung: { sehat: 15, karies: 4, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 1, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 23, karies: 1, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 2, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 5,
    dmft: 5,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: true, perluDirujuk: false, dirujukKe: "tidak_dirujuk" },
    createdBy: "System Import"
  },
  {
    nama: "R013",
    tanggalPemeriksaan: "2026-07-13",
    tanggalInput: "2026-07-13",
    umur: 14,
    jenisKelamin: "Laki-laki",
    kelompokUmur: "10-18",
    alamat: "Alamat Dummy 13",
    noTelepon: "08100000013",
    namaOrangTua: "Orang Tua R013",
    pendidikan: "SMP",
    pekerjaan: "ASN/PNS/PPPK",
    gigiSulung: { sehat: 16, karies: 1, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 2, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 19, karies: 4, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 3, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 4,
    dmft: 9,
    mukosa: { gusiBerdarah: true, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: true, perluPerawatanTidakSegera: false, perluDirujuk: true, dirujukKe: "puskesmas" },
    createdBy: "System Import"
  },
  {
    nama: "R014",
    tanggalPemeriksaan: "2026-07-14",
    tanggalInput: "2026-07-14",
    umur: 9,
    jenisKelamin: "Perempuan",
    kelompokUmur: "5-10",
    alamat: "Alamat Dummy 14",
    noTelepon: "08100000014",
    namaOrangTua: "Orang Tua R014",
    pendidikan: "SMA",
    pekerjaan: "PEGAWAI SWASTA",
    gigiSulung: { sehat: 12, karies: 3, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 3, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 24, karies: 2, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 0, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 8,
    dmft: 4,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: false, perluDirujuk: false, dirujukKe: "tidak_dirujuk" },
    createdBy: "System Import"
  },
  {
    nama: "R015",
    tanggalPemeriksaan: "2026-07-15",
    tanggalInput: "2026-07-15",
    umur: 12,
    jenisKelamin: "Laki-laki",
    kelompokUmur: "10-18",
    alamat: "Alamat Dummy 15",
    noTelepon: "08100000015",
    namaOrangTua: "Orang Tua R015",
    pendidikan: "S1/D4",
    pekerjaan: "PENGURUS/IBU RUMAH TANGGA",
    gigiSulung: { sehat: 20, karies: 0, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 0, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 27, karies: 0, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 1, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 0,
    dmft: 1,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: true, perluDirujuk: true, dirujukKe: "puskesmas" },
    createdBy: "System Import"
  },
  {
    nama: "R016",
    tanggalPemeriksaan: "2026-07-16",
    tanggalInput: "2026-07-16",
    umur: 7,
    jenisKelamin: "Perempuan",
    kelompokUmur: "5-10",
    alamat: "Alamat Dummy 16",
    noTelepon: "08100000016",
    namaOrangTua: "Orang Tua R016",
    pendidikan: "SD",
    pekerjaan: "WIRASWASTA/WIRAUSAHA",
    gigiSulung: { sehat: 16, karies: 2, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 1, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 23, karies: 3, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 2, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 4,
    dmft: 5,
    mukosa: { gusiBerdarah: true, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: true, perluPerawatanTidakSegera: false, perluDirujuk: false, dirujukKe: "tidak_dirujuk" },
    createdBy: "System Import"
  },
  {
    nama: "R017",
    tanggalPemeriksaan: "2026-07-17",
    tanggalInput: "2026-07-17",
    umur: 10,
    jenisKelamin: "Laki-laki",
    kelompokUmur: "5-10",
    alamat: "Alamat Dummy 17",
    noTelepon: "08100000017",
    namaOrangTua: "Orang Tua R017",
    pendidikan: "SMP",
    pekerjaan: "PEGAWAI SWASTA",
    gigiSulung: { sehat: 12, karies: 4, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 2, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 24, karies: 1, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 3, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 8,
    dmft: 4,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: false, perluDirujuk: true, dirujukKe: "puskesmas" },
    createdBy: "System Import"
  },
  {
    nama: "R018",
    tanggalPemeriksaan: "2026-07-18",
    tanggalInput: "2026-07-18",
    umur: 13,
    jenisKelamin: "Perempuan",
    kelompokUmur: "10-18",
    alamat: "Alamat Dummy 18",
    noTelepon: "08100000018",
    namaOrangTua: "Orang Tua R018",
    pendidikan: "SMA",
    pekerjaan: "ASN/PNS/PPPK",
    gigiSulung: { sehat: 16, karies: 1, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 3, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 24, karies: 4, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 0, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 4,
    dmft: 4,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: true, perluDirujuk: false, dirujukKe: "tidak_dirujuk" },
    createdBy: "System Import"
  },
  {
    nama: "R019",
    tanggalPemeriksaan: "2026-07-19",
    tanggalInput: "2026-07-19",
    umur: 8,
    jenisKelamin: "Laki-laki",
    kelompokUmur: "5-10",
    alamat: "Alamat Dummy 19",
    noTelepon: "08100000019",
    namaOrangTua: "Orang Tua R019",
    pendidikan: "S1/D4",
    pekerjaan: "PEGAWAI SWASTA",
    gigiSulung: { sehat: 16, karies: 3, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 0, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 25, karies: 2, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 1, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 4,
    dmft: 3,
    mukosa: { gusiBerdarah: true, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: true, perluPerawatanTidakSegera: false, perluDirujuk: true, dirujukKe: "puskesmas" },
    createdBy: "System Import"
  },
  {
    nama: "R020",
    tanggalPemeriksaan: "2026-07-20",
    tanggalInput: "2026-07-20",
    umur: 11,
    jenisKelamin: "Perempuan",
    kelompokUmur: "10-18",
    alamat: "Alamat Dummy 20",
    noTelepon: "08100000020",
    namaOrangTua: "Orang Tua R020",
    pendidikan: "SD",
    pekerjaan: "PENGURUS/IBU RUMAH TANGGA",
    gigiSulung: { sehat: 17, karies: 0, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 1, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 25, karies: 0, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 2, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 3,
    dmft: 3,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: false, perluDirujuk: false, dirujukKe: "tidak_dirujuk" },
    createdBy: "System Import"
  },
  {
    nama: "R021",
    tanggalPemeriksaan: "2026-07-21",
    tanggalInput: "2026-07-21",
    umur: 14,
    jenisKelamin: "Laki-laki",
    kelompokUmur: "10-18",
    alamat: "Alamat Dummy 21",
    noTelepon: "08100000021",
    namaOrangTua: "Orang Tua R021",
    pendidikan: "SMP",
    pekerjaan: "WIRASWASTA/WIRAUSAHA",
    gigiSulung: { sehat: 16, karies: 2, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 2, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 21, karies: 3, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 3, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 4,
    dmft: 7,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: true, perluDirujuk: true, dirujukKe: "puskesmas" },
    createdBy: "System Import"
  },
  {
    nama: "R022",
    tanggalPemeriksaan: "2026-07-22",
    tanggalInput: "2026-07-22",
    umur: 9,
    jenisKelamin: "Perempuan",
    kelompokUmur: "5-10",
    alamat: "Alamat Dummy 22",
    noTelepon: "08100000022",
    namaOrangTua: "Orang Tua R022",
    pendidikan: "SMA",
    pekerjaan: "PEGAWAI SWASTA",
    gigiSulung: { sehat: 12, karies: 4, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 3, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 26, karies: 1, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 0, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 8,
    dmft: 2,
    mukosa: { gusiBerdarah: true, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: true, perluPerawatanTidakSegera: false, perluDirujuk: false, dirujukKe: "tidak_dirujuk" },
    createdBy: "System Import"
  },
  {
    nama: "R023",
    tanggalPemeriksaan: "2026-07-23",
    tanggalInput: "2026-07-23",
    umur: 12,
    jenisKelamin: "Laki-laki",
    kelompokUmur: "10-18",
    alamat: "Alamat Dummy 23",
    noTelepon: "08100000023",
    namaOrangTua: "Orang Tua R023",
    pendidikan: "S1/D4",
    pekerjaan: "ASN/PNS/PPPK",
    gigiSulung: { sehat: 17, karies: 1, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 0, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 22, karies: 4, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 1, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 3,
    dmft: 6,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: false, perluDirujuk: true, dirujukKe: "puskesmas" },
    createdBy: "System Import"
  },
  {
    nama: "R024",
    tanggalPemeriksaan: "2026-07-24",
    tanggalInput: "2026-07-24",
    umur: 7,
    jenisKelamin: "Perempuan",
    kelompokUmur: "5-10",
    alamat: "Alamat Dummy 24",
    noTelepon: "08100000024",
    namaOrangTua: "Orang Tua R024",
    pendidikan: "SD",
    pekerjaan: "PEGAWAI SWASTA",
    gigiSulung: { sehat: 15, karies: 3, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 1, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 1 },
    gigiTetap: { sehat: 23, karies: 2, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 2, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 4,
    dmft: 5,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: true, perluDirujuk: false, dirujukKe: "tidak_dirujuk" },
    createdBy: "System Import"
  },
  {
    nama: "R025",
    tanggalPemeriksaan: "2026-07-25",
    tanggalInput: "2026-07-25",
    umur: 10,
    jenisKelamin: "Laki-laki",
    kelompokUmur: "5-10",
    alamat: "Alamat Dummy 25",
    noTelepon: "08100000025",
    namaOrangTua: "Orang Tua R025",
    pendidikan: "SMP",
    pekerjaan: "PENGURUS/IBU RUMAH TANGGA",
    gigiSulung: { sehat: 17, karies: 0, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 2, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 23, karies: 0, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 3, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 3,
    dmft: 5,
    mukosa: { gusiBerdarah: true, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: true, perluPerawatanTidakSegera: false, perluDirujuk: true, dirujukKe: "puskesmas" },
    createdBy: "System Import"
  },
  {
    nama: "R026",
    tanggalPemeriksaan: "2026-07-26",
    tanggalInput: "2026-07-26",
    umur: 13,
    jenisKelamin: "Perempuan",
    kelompokUmur: "10-18",
    alamat: "Alamat Dummy 26",
    noTelepon: "08100000026",
    namaOrangTua: "Orang Tua R026",
    pendidikan: "SMA",
    pekerjaan: "WIRASWASTA/WIRAUSAHA",
    gigiSulung: { sehat: 13, karies: 2, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 3, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 23, karies: 3, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 0, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 7,
    dmft: 5,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: false, perluDirujuk: false, dirujukKe: "tidak_dirujuk" },
    createdBy: "System Import"
  },
  {
    nama: "R027",
    tanggalPemeriksaan: "2026-07-27",
    tanggalInput: "2026-07-27",
    umur: 8,
    jenisKelamin: "Laki-laki",
    kelompokUmur: "5-10",
    alamat: "Alamat Dummy 27",
    noTelepon: "08100000027",
    namaOrangTua: "Orang Tua R027",
    pendidikan: "S1/D4",
    pekerjaan: "PEGAWAI SWASTA",
    gigiSulung: { sehat: 15, karies: 4, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 0, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 1 },
    gigiTetap: { sehat: 24, karies: 1, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 1, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 4,
    dmft: 4,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: true, perluDirujuk: true, dirujukKe: "puskesmas" },
    createdBy: "System Import"
  },
  {
    nama: "R028",
    tanggalPemeriksaan: "2026-07-28",
    tanggalInput: "2026-07-28",
    umur: 11,
    jenisKelamin: "Perempuan",
    kelompokUmur: "10-18",
    alamat: "Alamat Dummy 28",
    noTelepon: "08100000028",
    namaOrangTua: "Orang Tua R028",
    pendidikan: "SD",
    pekerjaan: "ASN/PNS/PPPK",
    gigiSulung: { sehat: 17, karies: 1, dicabutKaries: 1, tumpatanKaries: 0, tumpatanTanpaKaries: 1, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 20, karies: 4, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 2, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 3,
    dmft: 8,
    mukosa: { gusiBerdarah: true, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: true, perluPerawatanTidakSegera: false, perluDirujuk: false, dirujukKe: "tidak_dirujuk" },
    createdBy: "System Import"
  },
  {
    nama: "R029",
    tanggalPemeriksaan: "2026-07-29",
    tanggalInput: "2026-07-29",
    umur: 14,
    jenisKelamin: "Laki-laki",
    kelompokUmur: "10-18",
    alamat: "Alamat Dummy 29",
    noTelepon: "08100000029",
    namaOrangTua: "Orang Tua R029",
    pendidikan: "SMP",
    pekerjaan: "PEGAWAI SWASTA",
    gigiSulung: { sehat: 13, karies: 3, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 2, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 0 },
    gigiTetap: { sehat: 21, karies: 2, dicabutKaries: 2, tumpatanKaries: 0, tumpatanTanpaKaries: 3, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 7,
    dmft: 7,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: false, perluDirujuk: true, dirujukKe: "puskesmas" },
    createdBy: "System Import"
  },
  {
    nama: "R030",
    tanggalPemeriksaan: "2026-07-30",
    tanggalInput: "2026-07-30",
    umur: 9,
    jenisKelamin: "Perempuan",
    kelompokUmur: "5-10",
    alamat: "Alamat Dummy 30",
    noTelepon: "08100000030",
    namaOrangTua: "Orang Tua R030",
    pendidikan: "SMA",
    pekerjaan: "PENGURUS/IBU RUMAH TANGGA",
    gigiSulung: { sehat: 16, karies: 0, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 3, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: 1 },
    gigiTetap: { sehat: 28, karies: 0, dicabutKaries: 0, tumpatanKaries: 0, tumpatanTanpaKaries: 0, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
    deft: 3,
    dmft: 0,
    mukosa: { gusiBerdarah: false, lesiMukosaOral: false },
    tindakLanjut: { perluPerawatanSegera: false, perluPerawatanTidakSegera: true, perluDirujuk: false, dirujukKe: "tidak_dirujuk" },
    createdBy: "System Import"
  }
];

// Helper to parse uploaded Excel files dynamically using XLSX library
export function parseExcelFileToRespondents(arrayBuffer: ArrayBuffer): Omit<RespondentData, 'id' | 'createdAt'>[] {
  const workbook = XLSX.read(arrayBuffer, { type: 'array' });
  const sheetName = workbook.SheetNames[0];
  const worksheet = workbook.Sheets[sheetName];
  const rawData: any[] = XLSX.utils.sheet_to_json(worksheet, { defval: '' });

  return rawData.map((row) => {
    const nama = String(row['Nama/Kode Responden'] || row['Kode Responden'] || row['Nama'] || row['No'] || `R-${Math.floor(Math.random()*1000)}`).trim();
    const tgl = String(row['Tanggal Pemeriksaan'] || new Date().toISOString().split('T')[0]).trim();
    const umur = Number(row['Umur'] || 10);
    const genderRaw = String(row['Jenis Kelamin'] || 'Laki-laki').trim();
    const jenisKelamin: 'Laki-laki' | 'Perempuan' = (genderRaw.toLowerCase().includes('perempuan') || genderRaw.toLowerCase().includes('p')) ? 'Perempuan' : 'Laki-laki';
    
    let kelompokUmur: '5-10' | '10-18' | '18-60' | '60+' = '5-10';
    if (umur > 60) kelompokUmur = '60+';
    else if (umur >= 18) kelompokUmur = '18-60';
    else if (umur >= 11) kelompokUmur = '10-18';

    const eduRaw = String(row['Pendidikan Terakhir Orang Tua'] || row['Pendidikan'] || 'SMA').trim();
    let pendidikan: any = 'SMA';
    if (eduRaw.includes('SD')) pendidikan = 'SD';
    else if (eduRaw.includes('SMP')) pendidikan = 'SMP';
    else if (eduRaw.includes('Perguruan') || eduRaw.includes('S1') || eduRaw.includes('Diploma')) pendidikan = 'S1/D4';
    else if (eduRaw.includes('Tidak')) pendidikan = 'Tidak Sekolah';

    const occRaw = String(row['Pekerjaan Orang Tua'] || row['Pekerjaan'] || 'PEGAWAI SWASTA').trim();
    let pekerjaan: any = 'PEGAWAI SWASTA';
    if (occRaw.includes('Wiraswasta')) pekerjaan = 'WIRASWASTA/WIRAUSAHA';
    else if (occRaw.includes('PNS') || occRaw.includes('ASN')) pekerjaan = 'ASN/PNS/PPPK';
    else if (occRaw.includes('Rumah Tangga')) pekerjaan = 'PENGURUS/IBU RUMAH TANGGA';

    const d = Number(row['Gigi Sulung Karies (d)'] ?? 0);
    const e = Number(row['Gigi Sulung Dicabut karena Karies (e)'] ?? 0);
    const f = Number(row['Gigi Sulung Tumpatan (f)'] ?? 0);
    const K = Number(row['Gigi Sulung Sudah Tanggal Fisiologis (K)'] ?? 0);
    const deftCalculated = d + e + f; // K is NOT counted in def-t

    const D = Number(row['Gigi Tetap Karies (D)'] ?? 0);
    const M = Number(row['Gigi Tetap Dicabut karena Karies (M)'] ?? 0);
    const F = Number(row['Gigi Tetap Tumpatan (F)'] ?? 0);
    const dmftCalculated = D + M + F;

    const mukosaRaw = String(row['Kondisi Gusi/Mukosa'] || '').trim();
    const isGingivitis = mukosaRaw.toLowerCase().includes('gingivitis') || mukosaRaw.toLowerCase().includes('berdarah');
    const isLesi = mukosaRaw.toLowerCase().includes('lesi');

    const tindakLanjutRaw = String(row['Tindak Lanjut'] || '').trim();
    const statusRujukanRaw = String(row['Status Rujukan'] || '').trim();
    const perluRujukan = statusRujukanRaw.toLowerCase().includes('perlu rujukan') && !statusRujukanRaw.toLowerCase().includes('tidak');

    return {
      nama,
      tanggalPemeriksaan: tgl,
      tanggalInput: tgl,
      umur,
      jenisKelamin,
      kelompokUmur,
      alamat: String(row['Alamat'] || '').trim(),
      noTelepon: String(row['No. Telepon'] || '').trim(),
      namaOrangTua: String(row['Nama Orang Tua'] || '').trim(),
      pendidikan,
      pekerjaan,
      gigiSulung: { sehat: Math.max(0, 20 - deftCalculated), karies: d, dicabutKaries: e, tumpatanKaries: 0, tumpatanTanpaKaries: f, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0, sudahTanggal: K },
      gigiTetap: { sehat: Math.max(0, 28 - dmftCalculated), karies: D, dicabutKaries: M, tumpatanKaries: 0, tumpatanTanpaKaries: F, dicabutSebabLain: 0, fissureSealant: 0, protesaCekat: 0, tidakTumbuh: 0, lainLain: 0 },
      deft: deftCalculated,
      dmft: dmftCalculated,
      mukosa: { gusiBerdarah: isGingivitis, lesiMukosaOral: isLesi },
      tindakLanjut: {
        perluPerawatanSegera: tindakLanjutRaw.toLowerCase().includes('perawatan'),
        perluPerawatanTidakSegera: tindakLanjutRaw.toLowerCase().includes('edukasi'),
        perluDirujuk: perluRujukan,
        dirujukKe: perluRujukan ? 'puskesmas' : 'tidak_dirujuk'
      },
      createdBy: 'Excel Import'
    };
  });
}
